@startuml Diagram of Modules 

left to right direction
skinparam linetype polyline


node API {
    [API Gateway]
}

node Sandwich{
    [Sandwich Service] <<Component>> as sandwichService
    [Sandwich Database] <<Component>> as sandwichDatabase
    sandwichService ..> sandwichDatabase
}

node Ingredient{
    [Ingredient Service] <<Component>> as ingredientService
    [Ingredient Database] <<Component>> as ingredientDatabase
    ingredientService ..> ingredientDatabase
}

node Review{
    [Review Service] <<Component>> as reviewService
    [Review Database] <<Component>> as reviewDatabase
    reviewService ..> reviewDatabase
}

node Shop{
    [Shop Service] <<Component>> as shopService
    [Shop Database] <<Component>> as shopDatabase
    shopService ..> shopDatabase
}

node Order{
    [Order Service] <<Component>> as orderService
    [Order Database] <<Component>> as orderDatabase
    orderService ..> orderDatabase
}

node Customer{
    [Customer Service] <<Component>> as customerService
    [Customer Database] <<Component>> as customerDatabase
    customerService ..> customerDatabase
}


HTTP - [API Gateway]
[API Gateway] --(0 sandwichService
[API Gateway] --(0 ingredientService
[API Gateway] --(0 reviewService
[API Gateway] --(0 shopService
[API Gateway] --(0 orderService
[API Gateway] --(0 customerService




@enduml