@startuml

left to right direction

[Sandwich] <<microservice>> as sandwich
[Ingredient] <<microservice>> as ingredient
[Review] <<microservice>> as review
[Shop] <<microservice>> as shop
[Order] <<microservice>> as order
[Customer] <<microservice>> as customer


node "RabbitMQ"{
    queue sendSandwich as sendSandwich{ 
    }
    queue sendIngredient as sendIngredient{
    }
    queue sendShop as sendShop{
    }
    queue sendCustomer as sendCustomer{
    }
    queue sendOrder as sendOrder{
    }

}

database "Sandwich Database" as sand{
}
database "Ingredient Database" as i{
}
database "Review Database" as r{
}
database "Shop Database" as s{
}
database "Order Database" as o{
}
database "Customer Database" as c{
}

sandwich <-right-> sand
ingredient <-right-> i
review <-right-> r 
shop <--> s
order <-right-> o 
customer <--> c

sendSandwich <-- sandwich
order <-- sendSandwich
ingredient --> sendIngredient
sendIngredient --> sandwich
sendShop <-- shop 
order <-- sendShop
sendCustomer <-left- customer
order <-- sendCustomer
sendCustomer --> review
order --> sendOrder
sendOrder --> review

@enduml