@startuml
  class Customer {
    - customerId: int
    - name: string
    - taxIdenticationNumber: string
    - email: string
    - address: string
  }

  class AuthorizationData{

  }

  class Role{
    - designation : string
  }
  class Sandwich {
    - sandwichId: int
    - designation: string
    - sellingPrice: float
  }

  class Description{
    - text: string
    - language: string
  }

  class Ingredient {
    - ingredientId: int
    - designation: string
  }

  class Review{
    - userId: int
    - reviewId: int
    - sandwichId: int
    - text: string
    - likes: int
    - dislikes: int
  }

  class Shop{
    - shopId: int
    - designation: string
    - address: string
  }

  class PersonInCharge{
    - personId: int
    - name: string
    - email: string
  }

  class OpeningHours{
    - openingHoursId: int
    - shopId: int
    - dayOfTheWeek: int
    - time: Date
  }

  class Order{
    - orderId: int
    - customerId: int
    - shopId: int
    - dateOfDelivery: Date
    - totalPrice: float
    - status: string
  }

  class SandwichDelivery{
    - orderId: int
    - sandwichId: int
    - quantity: int
  }

  class IngredientsInSandwich{
    - sandwichId: int
    - ingredientId: int
  }

  Customer "1" --- "*" AuthorizationData: has >
  AuthorizationData "1" --- "*" Role: has >
  Sandwich "*" --- "*" Ingredient: has >
  (Sandwich,Ingredient) .. IngredientsInSandwich
  Sandwich "1" --- "*" Description: has >
  Shop "1" --- "*" OpeningHours: has >
  Shop --> PersonInCharge: has >
  Order "*" --- "*" Sandwich: has >
  (Order, Sandwich) .. SandwichDelivery
  Customer "1" --- "*" Order: makes >
  Customer "1" --- "*" Review: makes >
  Sandwich "1" --- "*" Review: has >
  Order "*" --- "1" Shop: fullfills <

@enduml