@startuml Domain Model
  class Customer {
  }

  class PersonInCharge{
  }

  class Person{
    - personId: int
    - name: string
    - taxIdenticationNumber: string
    - email: string

  }

  class Address{
    - zipCode: string
    - streetName: string
    - doorNumber: int
    - location: string
    - country: string

  }

  class AuthorizationData{

  }

  class Role{
    - designation : string
  }
  class Sandwich {
    - sandwichId: int
    - designation: string
    - sellingPrice: float
    - isActive: boolean
  }

  class Description{
    - text: string
    - language: ISO
  }

  class Ingredient {
    - ingredientId: int
    - designation: string
    - isActive: boolean
  }
  class Category{
    - class: string
  }

  class Review{
    - comment: string
    - rating: int
  }

  class Shop{
    - shopId: int
    - designation: string
  }

  class OpeningHours{
    - openingHoursId: int
    - dayOfTheWeek: int
    - time: Date
  }

  class Order{
    - orderId: int
    - dateOfDelivery: Date
    - dateOfCreation: Date
    - totalPrice: float
    - status: string
  }

  class OrderItem{
    - quantity: int
  }

  class ReviewAvaliation{
    - isLiked: boolean
    - dateOfCreation: Date
  }

  class Language{
    - language: string
  }


  Person "1" --- "*" AuthorizationData: has >
  Person "*" --- "*" Language: knows >
  AuthorizationData "1" --- "*" Role: has >
  Sandwich "*" --- "*" Ingredient: has >
  Sandwich "1" --- "*" Description: has >
  Shop "1" --- "*" OpeningHours: has >
  Shop --> PersonInCharge: has >
  Order "*" --- "*" OrderItem: has >
  Customer "1" --- "*" Order: makes >
  Customer "1" --- "*" Review: makes >
  Sandwich "1" --- "*" Review: has >
  Review "1" --- "*" ReviewAvaliation: has >
  Customer "1" --- "*" ReviewAvaliation: makes >
  Order "*" --- "1" Shop: fullfills <
  Ingredient "*" --- "1" Category: has >
  Shop "1" --- "1" Address: has >
  OrderItem "*" --- "1" Sandwich: has >
  Customer --|> Person
  PersonInCharge --|> Person
  Person "*" --- "*" Address: has >

@enduml