@startuml
left to right direction

[*] --> Criada

state Criada {
}

state "Em processo" as aprocessar {

}

state Processada {

}

state Entregue {
}

Criada --> aprocessar : prever
aprocessar   --> Processada: realizar
Processada  --> Entregue: entregar


@enduml