@startuml
left to right direction

[*] --> Criada

state Criada {
}

state Denunciada {

}

state c <<choice>>
state h <<choice>>
 

state Eliminada {

}


Criada --> c
c --> Denunciada: denunciada
Denunciada --> h
h   --> Eliminada: contém palavras ofensivas
h  --> Criada: não contém ofensivas


@enduml