@startuml

skinparam defaultTextAlignment center

left to right direction

:Utilizador Anónimo, \nPessoa responsável pela loja: as c
:Cliente: as cliente
:Administrador: as admin

(UC19 - Adicionar críticas a uma sanduíche) as UC19 
(UC20 - Votar numa crítica de uma sanduíche) as UC20
(UC21 - Listar todas as crítica de uma sanduíche) as UC21
(UC32 - Listar todas as críticas denunciadas) as UC32
(UC33 - Eliminar uma crítica denunciada por ID) as UC33
(UC36 - Denunciar uma crítica) as UC36
(UC43 & Editar uma crítica feita) as UC43
(UC44 - Listar todas as críticas feitas pelo cliente) as UC44
(UC45 - Eliminar critica feita pelo cliente) as UC45

cliente -- UC19
cliente -- UC20

cliente -- UC21
c -- UC21

UC32 -- admin
UC33 -- admin
UC21 -- admin
UC44 -- admin
UC45 -- admin

cliente -- UC36
cliente -- UC43

cliente -- UC44
cliente -- UC45



@end