@startuml Users Cases Diagram 

left to right direction


:Utilizador Anónimo: as aCostumer
:Cliente: as rCostumer
:Administrador: as admin
:Pessoa responsável: as person


(UC01 & Criar um ingrediente) as UC01
(UC02 & Obter um ingrediente por ID) as UC02
(UC03 & Obter um ingrediente por designação) as UC03
(UC04 & Obter todos os ingredientes) as UC04

(UC05 & Criar uma sanduíche) as UC05
(UC06 & Obter uma sanduíche por ID) as UC06
(UC07 & Obter todas as sanduíches) as UC07
(UC08 & Adicionar ingrediente/s a uma sanduíche) as UC08
(UC09 & Adicionar descrição/ões a uma sanduíche) as UC09
(UC10 & Obter todas as sanduíches que não possuam um ingrediente específico) as UC10

(UC11 & Adicionar cliente) as UC11
(UC12 & Obter cliente por ID) as UC12
(UC13 & Obter cliente por e-mail) as UC13
(UC14 & Obter cliente por número de identificação fiscal) as UC14
(UC15 & Obter dados de autenticação do cliente) as UC15
(UC16 & Obter todos os clientes) as UC16
(UC17 & Adicionar permissões a um usuário) as UC17
(UC18 & Gerar JWT) as UC18

(UC19 & Adicionar crítica a uma sanduíche) as UC19 
(UC20 & Votar numa crítica de uma sanduíche) as UC20
(UC21 & Listar todas as críticas de uma sanduíche) as UC21

(UC22 & Criar loja) as UC22
(UC23 & Listar todas as lojas) as UC23
(UC24 & Listar loja por ID) as UC24
(UC25 & Listar loja por designação) as UC25
(UC26 & Listar loja por endereço) as UC26


(UC27 & Criar uma encomenda) as UC27
(UC28 & Listar encomendas de uma loja) as UC28
(UC29 & Eliminar ingredientes) as UC29


(UC30 & Eliminar sanduíches) as UC30
(UC31 & Eliminar lojas) as UC31
(UC32 & Listar todas as criticas denunciadas) as UC32
(UC33 & Eliminar uma critica por ID) as UC33
(UC34 & Alterar os dados de uma sanduíche) as UC34
(UC35 & Obter todos os ingredientes da uma certa categoria) as UC35
(UC36 & Denunciar uma crítica) as UC36
(UC37 & Alterar a estado da encomenda) as UC37
(UC38 & Retirar a minha encomenda) as UC38
(UC39 & Listar as minhas encomendas) as UC39

(UC40 & Alterar os meus dados) as UC40
(UC41 & Visualizar os meus dados) as UC41
(UC42 & Editar os dados de uma loja) as UC42
(UC43 & Editar uma crítica feita) as UC43
(UC44 & Listar todas as críticas feitas pelo cliente) as UC44
(UC45 & Eliminar critica feita pelo cliente) as UC45


@enduml


