@startuml

skinparam defaultTextAlignment center

left to right direction

:Cliente: as c
:Pessoa responsável pela loja: as person

(UC27 - Criar uma encomenda) as UC27
(UC28 - Listar encomendas de uma loja) as UC28
(UC37 - Alterar a estado da encomenda) as UC37
(UC39 - Listar as encomendas do cliente) as UC39

c -- UC27
person -- UC28
person -- UC37
c -- UC39
person -- UC39


@end