@startuml

skinparam defaultTextAlignment center

left to right direction

:Utilizador Anónimo, \nCliente, \nPessoa responsável pela loja: as c
:Administrador: as admin

(UC01 - Criar um ingrediente) as UC01
(UC02 - Obter um ingrediente por ID) as UC02
(UC03 - Obter um ingrediente por designação) as UC03
(UC04 - Obter todos os ingredientes) as UC04
(UC29 - Alterar estado de um ingrediente) as UC29
(UC35 - Obter todos os ingredientes de uma certa categoria) as UC35

UC01 -- admin
UC29 -- admin
UC02 -- admin
UC03 -- admin
UC04 -- admin
UC35 -- admin

c -- UC02
c -- UC03
c -- UC04
c -- UC35
@end